/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpati223;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static simpati223.FSurat_Masuk.hideJTableColumn;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static simpati223.FSurat_Masuk.hideJTableColumn;
import simpati223.Fungsi;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import static simpati223.FSiswa.hideJTableColumn;
import static simpati223.FSurat_Keterangan.hideJTableColumn;

/**
 *
 * @author Ikhsan Abdillah
 */
public class FLaporan_Surat_Keterangan_Pertahun extends javax.swing.JInternalFrame {

    /**
     * Creates new form FLaporan_Surat_Keterangan_Pertahun
     */
    public FLaporan_Surat_Keterangan_Pertahun() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jYearChooser2 = new com.toedter.calendar.JYearChooser();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Laporan Surat Keterangan Pertahun");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N

        jButton1.setText("CETAK");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jYearChooser2.setPreferredSize(new java.awt.Dimension(47, 25));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jYearChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Surat", "Tanggal Surat", "Yang bertanda tangan", "Menerangkan kepada"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setToolTipText("");
        jPanel3.setName(""); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel DftTblModel_Surat_Keterangan;
    private String SQL;
    
    public static void hideJTableColumn(TableColumn tc) {
       lockJTableColumnWidth(tc, 0);
   }

   public static void lockJTableColumnWidth(TableColumn tc, int pixels) {
       if (tc != null) {
           tc.setMinWidth(pixels);
           tc.setMaxWidth(pixels);
           tc.setPreferredWidth(pixels);
           tc.setResizable(false);
       }
   }
   
     public void TampilData() {
        DftTblModel_Surat_Keterangan = new DefaultTableModel();
        DftTblModel_Surat_Keterangan.addColumn("id");
        DftTblModel_Surat_Keterangan.addColumn("No Surat");
        DftTblModel_Surat_Keterangan.addColumn("Tanggal Surat");
        DftTblModel_Surat_Keterangan.addColumn("Yang bertanda tangan");
        DftTblModel_Surat_Keterangan.addColumn("Menerangkan Kepada");
        DftTblModel_Surat_Keterangan.addColumn("Keterangan");
        jTable1.setModel(DftTblModel_Surat_Keterangan);

        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT a.*, b.nama as nama_guru, c.nama as nama_siswa FROM surat_keterangan a " +
                  "LEFT JOIN guru b ON a.id_guru = b.id "+
                  "LEFT JOIN siswa c ON a.id_siswa = c.id";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
               DftTblModel_Surat_Keterangan.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nomor_surat"), //tampilin ke layar
                    res.getString("tgl_surat"),//tampilin ke layar
                    res.getString("nama_guru"), //tampilin ke layar
                    res.getString("nama_siswa"),//tampilin ke layar
                    res.getString("keterangan")
                });
            }
        hideJTableColumn(jTable1.getColumnModel().getColumn(0));
        hideJTableColumn(jTable1.getColumnModel().getColumn(5));
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        try {
            String folderPath = "C:\\simpati223";
            int year = jYearChooser2.getYear();
            String date = Integer.toString(year);
            System.out.println(date);
            String filePath = "C:\\simpati223\\laporan_surat_ketengan_tahun_"+date+".pdf";

            // Check if folder exists, create if it doesn't
            File folder = new File(folderPath);
            if (!folder.exists()) {
                boolean created = folder.mkdirs();
                if (created) {
                    System.out.println("Folder created successfully");
                } else {
                    System.out.println("Failed to create folder");
                }
            } else {
                System.out.println("Folder already exists");
            }

            // Check if file exists, create if it doesn't
            File file = new File(filePath);
            if (!file.exists()) {
                try {
                    boolean created = file.createNewFile();
                    if (created) {
                        //after created file, then we can create a content from pdf
                        Document document = new Document();
                        PdfWriter.getInstance(document, new FileOutputStream(filePath));

                        document.open();

                        //created a title from pdf
                        Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                        Paragraph para = new Paragraph("Laporan Surat Ketengan Tahun "+date, boldFont);
                        para.setAlignment(Element.ALIGN_CENTER);

                        document.add(para);

                        // then we create a table with five columns
                        //the column is no urut, no surat, tgl surat, asal surat, perihal
                        PdfPTable table = new PdfPTable(5);

                        // Set table properties
                        table.setWidthPercentage(100);
                        table.setSpacingBefore(40f);

                        // Set column widths
                        float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                        table.setWidths(columnWidths);

                        // Add table cells
                        Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                        table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                        //we generate data from table surat_masuk
                        java.sql.Statement stmt = conn.createStatement();
                        int no = 0;
                        String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                "LEFT JOIN guru b ON a.id_guru = b.id "+
                                "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                "where YEAR(tgl_surat) = '"+date+"'";
                        java.sql.ResultSet res = stmt.executeQuery(SQL);
                        Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                        while (res.next()) {
                            no++;
                            table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                            // Apply styling to body cells
                            table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(no).getCells()[1].setPaddingLeft(4f);
                            table.getRow(no).getCells()[2].setPaddingLeft(4f);
                            table.getRow(no).getCells()[3].setPaddingLeft(4f);
                            table.getRow(no).getCells()[4].setPaddingLeft(4f);
                        }

                        // Apply styling to header cells
                        table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                        // Add the table to the document
                        document.add(table);

                        document.close();
                        System.out.println("File created successfully");
                    } else {
                        System.out.println("Failed to create file");
                    }
                } catch (IOException e) {
                    System.out.println("An error occurred while creating the file: " + e.getMessage());
                }
            } else {
                //if file exist, then we can create the content from pdf
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(filePath));

                document.open();

                //created a title from pdf
                Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                Paragraph para = new Paragraph("Laporan Surat Keterangan Tahun "+date, boldFont);
                para.setAlignment(Element.ALIGN_CENTER);

                document.add(para);

                // then we create a table with five columns
                //the column is no urut, no surat, tgl surat, asal surat, perihal
                PdfPTable table = new PdfPTable(5);

                // Set table properties
                table.setWidthPercentage(100);
                table.setSpacingBefore(40f);

                // Set column widths
                float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                table.setWidths(columnWidths);

                // Add table cells
                Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                //we generate data from table surat_masuk
                java.sql.Statement stmt = conn.createStatement();
                int no = 0;
                String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                "LEFT JOIN guru b ON a.id_guru = b.id "+
                                "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                "where YEAR(tgl_surat) = '"+date+"'";
                java.sql.ResultSet res = stmt.executeQuery(SQL);
                Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                while (res.next()) {
                    no++;
                    table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                    // Apply styling to body cells
                    table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(no).getCells()[1].setPaddingLeft(4f);
                    table.getRow(no).getCells()[2].setPaddingLeft(4f);
                    table.getRow(no).getCells()[3].setPaddingLeft(4f);
                    table.getRow(no).getCells()[4].setPaddingLeft(4f);
                }

                // Apply styling to header cells
                table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                // Add the table to the document
                document.add(table);

                document.close();
                System.out.println("File created successfully");
            }
            File file1 = new File(filePath);

            JOptionPane.showMessageDialog(null, "Data berhasil dicetak", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            // Open the URL in the default web browser
            Desktop.getDesktop().open(file1);
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            Connection conn = Koneksi.getConnection();
            try {
                String folderPath = "C:\\simpati223";
                int year = jYearChooser2.getYear();
                String date = Integer.toString(year);
                System.out.println(date);
                String filePath = "C:\\simpati223\\laporan_surat_ketengan_tahun_"+date+".pdf";

                // Check if folder exists, create if it doesn't
                File folder = new File(folderPath);
                if (!folder.exists()) {
                    boolean created = folder.mkdirs();
                    if (created) {
                        System.out.println("Folder created successfully");
                    } else {
                        System.out.println("Failed to create folder");
                    }
                } else {
                    System.out.println("Folder already exists");
                }

                // Check if file exists, create if it doesn't
                File file = new File(filePath);
                if (!file.exists()) {
                    try {
                        boolean created = file.createNewFile();
                        if (created) {
                            //after created file, then we can create a content from pdf
                            Document document = new Document();
                            PdfWriter.getInstance(document, new FileOutputStream(filePath));

                            document.open();

                            //created a title from pdf
                            Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                            Paragraph para = new Paragraph("Laporan Surat Ketengan Tahun "+date, boldFont);
                            para.setAlignment(Element.ALIGN_CENTER);

                            document.add(para);

                            // then we create a table with five columns
                            //the column is no urut, no surat, tgl surat, asal surat, perihal
                            PdfPTable table = new PdfPTable(5);

                            // Set table properties
                            table.setWidthPercentage(100);
                            table.setSpacingBefore(40f);

                            // Set column widths
                            float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                            table.setWidths(columnWidths);

                            // Add table cells
                            Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                            table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                            //we generate data from table surat_masuk
                            java.sql.Statement stmt = conn.createStatement();
                            int no = 0;
                            String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                    "LEFT JOIN guru b ON a.id_guru = b.id "+
                                    "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                    "where YEAR(tgl_surat) = '"+date+"'";
                            java.sql.ResultSet res = stmt.executeQuery(SQL);
                            Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                            while (res.next()) {
                                no++;
                                table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                                // Apply styling to body cells
                                table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                                table.getRow(no).getCells()[1].setPaddingLeft(4f);
                                table.getRow(no).getCells()[2].setPaddingLeft(4f);
                                table.getRow(no).getCells()[3].setPaddingLeft(4f);
                                table.getRow(no).getCells()[4].setPaddingLeft(4f);
                            }

                            // Apply styling to header cells
                            table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                            // Add the table to the document
                            document.add(table);

                            document.close();
                            System.out.println("File created successfully");
                        } else {
                            System.out.println("Failed to create file");
                        }
                    } catch (IOException e) {
                        System.out.println("An error occurred while creating the file: " + e.getMessage());
                    }
                } else {
                    //if file exist, then we can create the content from pdf
                    Document document = new Document();
                    PdfWriter.getInstance(document, new FileOutputStream(filePath));

                    document.open();

                    //created a title from pdf
                    Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                    Paragraph para = new Paragraph("Laporan Surat Keterangan Tahun "+date, boldFont);
                    para.setAlignment(Element.ALIGN_CENTER);

                    document.add(para);

                    // then we create a table with five columns
                    //the column is no urut, no surat, tgl surat, asal surat, perihal
                    PdfPTable table = new PdfPTable(5);

                    // Set table properties
                    table.setWidthPercentage(100);
                    table.setSpacingBefore(40f);

                    // Set column widths
                    float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                    table.setWidths(columnWidths);

                    // Add table cells
                    Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                    table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                    //we generate data from table surat_masuk
                    java.sql.Statement stmt = conn.createStatement();
                    int no = 0;
                    String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                    "LEFT JOIN guru b ON a.id_guru = b.id "+
                                    "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                    "where YEAR(tgl_surat) = '"+date+"'";
                    java.sql.ResultSet res = stmt.executeQuery(SQL);
                    Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                    while (res.next()) {
                        no++;
                        table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                        // Apply styling to body cells
                        table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(no).getCells()[1].setPaddingLeft(4f);
                        table.getRow(no).getCells()[2].setPaddingLeft(4f);
                        table.getRow(no).getCells()[3].setPaddingLeft(4f);
                        table.getRow(no).getCells()[4].setPaddingLeft(4f);
                    }

                    // Apply styling to header cells
                    table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                    // Add the table to the document
                    document.add(table);

                    document.close();
                    System.out.println("File created successfully");
                }
                File file1 = new File(filePath);

                JOptionPane.showMessageDialog(null, "Data berhasil dicetak", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                // Open the URL in the default web browser
                Desktop.getDesktop().open(file1);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JYearChooser jYearChooser2;
    // End of variables declaration//GEN-END:variables
}
