/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpati223;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static simpati223.FSurat_Keterangan.hideJTableColumn;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import static simpati223.FSurat_Keterangan.hideJTableColumn;
import simpati223.Fungsi;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import static simpati223.FSiswa.hideJTableColumn;
import static simpati223.FSurat_Keterangan.hideJTableColumn;


/**
 *
 * @author Amos
 */
public class FLaporan_Surat_Keterangan_Perbulan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FLaporan_Surat_Keterangan_Perbulan
     */
    public FLaporan_Surat_Keterangan_Perbulan() {
        initComponents();
        TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jButton3 = new javax.swing.JButton();
        jYearChooser3 = new com.toedter.calendar.JYearChooser();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Laporan Surat Keterangan Perbulan");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setToolTipText("");
        jPanel6.setName(""); // NOI18N

        jButton3.setText("CETAK");
        jButton3.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jYearChooser3.setPreferredSize(new java.awt.Dimension(47, 25));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jYearChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jYearChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Surat", "Tanggal Surat", "Yang bertanda tangan", "Menerangkan kepada"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setToolTipText("");
        jPanel9.setName(""); // NOI18N

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Batal");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private DefaultTableModel DftTblModel_Surat_Keterangan;
    private String SQL;
    
    public static void hideJTableColumn(TableColumn tc) {
       lockJTableColumnWidth(tc, 0);
   }

   public static void lockJTableColumnWidth(TableColumn tc, int pixels) {
       if (tc != null) {
           tc.setMinWidth(pixels);
           tc.setMaxWidth(pixels);
           tc.setPreferredWidth(pixels);
           tc.setResizable(false);
       }
   }
   
     public void TampilData() {
        DftTblModel_Surat_Keterangan = new DefaultTableModel();
        DftTblModel_Surat_Keterangan.addColumn("id");
        DftTblModel_Surat_Keterangan.addColumn("No Surat");
        DftTblModel_Surat_Keterangan.addColumn("Tanggal Surat");
        DftTblModel_Surat_Keterangan.addColumn("Yang bertanda tangan");
        DftTblModel_Surat_Keterangan.addColumn("Menerangkan Kepada");
        DftTblModel_Surat_Keterangan.addColumn("Keterangan");
       jTable2.setModel(DftTblModel_Surat_Keterangan);

        Connection conn = Koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "SELECT a.*, b.nama as nama_guru, c.nama as nama_siswa FROM surat_keterangan a " +
                  "LEFT JOIN guru b ON a.id_guru = b.id "+
                  "LEFT JOIN siswa c ON a.id_siswa = c.id";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
               DftTblModel_Surat_Keterangan.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nomor_surat"), //tampilin ke layar
                    res.getString("tgl_surat"),//tampilin ke layar
                    res.getString("nama_guru"), //tampilin ke layar
                    res.getString("nama_siswa"),//tampilin ke layar
                    res.getString("keterangan")
                });
            }
        hideJTableColumn(jTable2.getColumnModel().getColumn(0));
        hideJTableColumn(jTable2.getColumnModel().getColumn(5));
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Connection conn = Koneksi.getConnection();
        try {
            String folderPath = "C:\\simpati223";
            String month = Fungsi.getMonthReport(jMonthChooser1.getMonth());
            int year = jYearChooser3.getYear();
            String date = Integer.toString(year)+"-"+month;
            String filePath = "C:\\simpati223\\laporan_surat_keterangan_perbulan_"+Fungsi.getMonthName(date)+".pdf";

            // Check if folder exists, create if it doesn't
            File folder = new File(folderPath);
            if (!folder.exists()) {
                boolean created = folder.mkdirs();
                if (created) {
                    System.out.println("Folder created successfully");
                } else {
                    System.out.println("Failed to create folder");
                }
            } else {
                System.out.println("Folder already exists");
            }

            // Check if file exists, create if it doesn't
            File file = new File(filePath);
            if (!file.exists()) {
                try {
                    boolean created = file.createNewFile();
                    if (created) {
                        //after created file, then we can create a content from pdf
                        Document document = new Document();
                        PdfWriter.getInstance(document, new FileOutputStream(filePath));

                        document.open();

                        //created a title from pdf
                        Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                        Paragraph para = new Paragraph("Laporan Surat Keterangan Bulan "+Fungsi.getMonthName(date)+" "+Fungsi.getYear(date), boldFont);
                        para.setAlignment(Element.ALIGN_CENTER);

                        document.add(para);

                        // then we create a table with five columns
                        //the column is no urut, no surat, tgl surat, asal surat, perihal
                        PdfPTable table = new PdfPTable(5);

                        // Set table properties
                        table.setWidthPercentage(100);
                        table.setSpacingBefore(40f);

                        // Set column widths
                        float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                        table.setWidths(columnWidths);

                        // Add table cells
                        Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                        table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                        table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                        //we generate data from table surat_masuk
                        java.sql.Statement stmt = conn.createStatement();
                        int no = 0;
                        String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                "LEFT JOIN guru b ON a.id_guru = b.id "+
                                "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                "where DATE_FORMAT(tgl_surat, '%Y-%m') = '"+date+"'";
                        java.sql.ResultSet res = stmt.executeQuery(SQL);
                        Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                        while (res.next()) {
                            no++;
                            table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                            table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                            // Apply styling to body cells
                            table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(no).getCells()[1].setPaddingLeft(4f);
                            table.getRow(no).getCells()[2].setPaddingLeft(4f);
                            table.getRow(no).getCells()[3].setPaddingLeft(4f);
                            table.getRow(no).getCells()[4].setPaddingLeft(4f);
                        }

                        // Apply styling to header cells
                        table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                        // Add the table to the document
                        document.add(table);

                        document.close();
                        System.out.println("File created successfully");
                    } else {
                        System.out.println("Failed to create file");
                    }
                } catch (IOException e) {
                    System.out.println("An error occurred while creating the file: " + e.getMessage());
                }
            } else {
                //if file exist, then we can create the content from pdf
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(filePath));

                document.open();

                //created a title from pdf
                Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                Paragraph para = new Paragraph("Laporan Surat Keterangan Bulan "+Fungsi.getMonthName(date)+" "+Fungsi.getYear(date), boldFont);
                para.setAlignment(Element.ALIGN_CENTER);

                document.add(para);

                // then we create a table with five columns
                //the column is no urut, no surat, tgl surat, asal surat, perihal
                PdfPTable table = new PdfPTable(5);

                // Set table properties
                table.setWidthPercentage(100);
                table.setSpacingBefore(40f);

                // Set column widths
                float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                table.setWidths(columnWidths);

                // Add table cells
                Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                //we generate data from table surat_masuk
                java.sql.Statement stmt = conn.createStatement();
                int no = 0;
                String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                "LEFT JOIN guru b ON a.id_guru = b.id "+
                                "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                "where DATE_FORMAT(tgl_surat, '%Y-%m') = '"+date+"'";
                java.sql.ResultSet res = stmt.executeQuery(SQL);
                Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                while (res.next()) {
                    no++;
                    table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                    table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                    // Apply styling to body cells
                    table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(no).getCells()[1].setPaddingLeft(4f);
                    table.getRow(no).getCells()[2].setPaddingLeft(4f);
                    table.getRow(no).getCells()[3].setPaddingLeft(4f);
                    table.getRow(no).getCells()[4].setPaddingLeft(4f);
                }

                // Apply styling to header cells
                table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                // Add the table to the document
                document.add(table);

                document.close();
                System.out.println("File created successfully");
            }
            File file1 = new File(filePath);

            JOptionPane.showMessageDialog(null, "Data berhasil dicetak", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            // Open the URL in the default web browser
            Desktop.getDesktop().open(file1);
        } catch (Exception e) {
            System.out.println(e);
        }
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            Connection conn = Koneksi.getConnection();
            try {
                String folderPath = "C:\\simpati223";
                String month = Fungsi.getMonthReport(jMonthChooser1.getMonth());
                int year = jYearChooser3.getYear();
                String date = Integer.toString(year)+"-"+month;
                String filePath = "C:\\simpati223\\laporan_surat_keterangan_perbulan_"+Fungsi.getMonthName(date)+".pdf";

                // Check if folder exists, create if it doesn't
                File folder = new File(folderPath);
                if (!folder.exists()) {
                    boolean created = folder.mkdirs();
                    if (created) {
                        System.out.println("Folder created successfully");
                    } else {
                        System.out.println("Failed to create folder");
                    }
                } else {
                    System.out.println("Folder already exists");
                }

                // Check if file exists, create if it doesn't
                File file = new File(filePath);
                if (!file.exists()) {
                    try {
                        boolean created = file.createNewFile();
                        if (created) {
                            //after created file, then we can create a content from pdf
                            Document document = new Document();
                            PdfWriter.getInstance(document, new FileOutputStream(filePath));

                            document.open();

                            //created a title from pdf
                            Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                            Paragraph para = new Paragraph("Laporan Surat Keterangan Bulan "+Fungsi.getMonthName(date)+" "+Fungsi.getYear(date), boldFont);
                            para.setAlignment(Element.ALIGN_CENTER);

                            document.add(para);

                            // then we create a table with five columns
                            //the column is no urut, no surat, tgl surat, asal surat, perihal
                            PdfPTable table = new PdfPTable(5);

                            // Set table properties
                            table.setWidthPercentage(100);
                            table.setSpacingBefore(40f);

                            // Set column widths
                            float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                            table.setWidths(columnWidths);

                            // Add table cells
                            Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                            table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                            table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                            //we generate data from table surat_masuk
                            java.sql.Statement stmt = conn.createStatement();
                            int no = 0;
                            String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                    "LEFT JOIN guru b ON a.id_guru = b.id "+
                                    "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                    "where DATE_FORMAT(tgl_surat, '%Y-%m') = '"+date+"'";
                            java.sql.ResultSet res = stmt.executeQuery(SQL);
                            Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                            while (res.next()) {
                                no++;
                                table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                                table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                                // Apply styling to body cells
                                table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                                table.getRow(no).getCells()[1].setPaddingLeft(4f);
                                table.getRow(no).getCells()[2].setPaddingLeft(4f);
                                table.getRow(no).getCells()[3].setPaddingLeft(4f);
                                table.getRow(no).getCells()[4].setPaddingLeft(4f);
                            }

                            // Apply styling to header cells
                            table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                            table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                            // Add the table to the document
                            document.add(table);

                            document.close();
                            System.out.println("File created successfully");
                        } else {
                            System.out.println("Failed to create file");
                        }
                    } catch (IOException e) {
                        System.out.println("An error occurred while creating the file: " + e.getMessage());
                    }
                } else {
                    //if file exist, then we can create the content from pdf
                    Document document = new Document();
                    PdfWriter.getInstance(document, new FileOutputStream(filePath));

                    document.open();

                    //created a title from pdf
                    Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, 17, Font.BOLD);
                    Paragraph para = new Paragraph("Laporan Surat Keterangan Bulan "+Fungsi.getMonthName(date)+" "+Fungsi.getYear(date), boldFont);
                    para.setAlignment(Element.ALIGN_CENTER);

                    document.add(para);

                    // then we create a table with five columns
                    //the column is no urut, no surat, tgl surat, asal surat, perihal
                    PdfPTable table = new PdfPTable(5);

                    // Set table properties
                    table.setWidthPercentage(100);
                    table.setSpacingBefore(40f);

                    // Set column widths
                    float[] columnWidths = {0.7f, 2f, 2f, 2f, 2f};
                    table.setWidths(columnWidths);

                    // Add table cells
                    Font headerFont = new Font(Font.FontFamily.TIMES_ROMAN, 10, Font.BOLD);
                    table.addCell(new PdfPCell(new Phrase("#", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("No Surat", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("Tgl Surat", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("Yang Bertanda Tangan", headerFont)));
                    table.addCell(new PdfPCell(new Phrase("Menerangkan Kepada", headerFont)));

                    //we generate data from table surat_masuk
                    java.sql.Statement stmt = conn.createStatement();
                    int no = 0;
                    String SQL = "select a.*, b.nama as nama_guru, c.nama as nama_siswa from surat_keterangan a " +
                                    "LEFT JOIN guru b ON a.id_guru = b.id "+
                                    "LEFT JOIN siswa c ON a.id_siswa = c.id " +
                                    "where DATE_FORMAT(tgl_surat, '%Y-%m') = '"+date+"'";
                    java.sql.ResultSet res = stmt.executeQuery(SQL);
                    Font bodyFont = new Font(Font.FontFamily.TIMES_ROMAN, 10);
                    while (res.next()) {
                        no++;
                        table.addCell(new PdfPCell(new Phrase(""+no, bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("nomor_surat"), bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("tgl_surat"), bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_guru"), bodyFont)));
                        table.addCell(new PdfPCell(new Phrase(""+res.getString("nama_siswa"), bodyFont)));

                        // Apply styling to body cells
                        table.getRow(no).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                        table.getRow(no).getCells()[1].setPaddingLeft(4f);
                        table.getRow(no).getCells()[2].setPaddingLeft(4f);
                        table.getRow(no).getCells()[3].setPaddingLeft(4f);
                        table.getRow(no).getCells()[4].setPaddingLeft(4f);
                    }

                    // Apply styling to header cells
                    table.getRow(0).getCells()[0].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[1].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[2].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[3].setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.getRow(0).getCells()[4].setHorizontalAlignment(Element.ALIGN_CENTER);

                    // Add the table to the document
                    document.add(table);

                    document.close();
                    System.out.println("File created successfully");
                }
                File file1 = new File(filePath);

                JOptionPane.showMessageDialog(null, "Data berhasil dicetak", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                // Open the URL in the default web browser
                Desktop.getDesktop().open(file1);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JYearChooser jYearChooser3;
    // End of variables declaration//GEN-END:variables
}
