/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpati223;

/**
 *
 * @author ASUS
 */
public class FMenu extends javax.swing.JFrame {

    /**
     * Creates new form FMenu
     */
    public FMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 204));
        jMenuBar1.setForeground(new java.awt.Color(0, 153, 204));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(222, 50));

        jMenu6.setText("Master");

        jMenuItem2.setText("Pengguna");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuItem2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem2KeyPressed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem3.setText("Guru");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuItem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem3KeyPressed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setText("Siswa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuItem4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem4KeyPressed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuBar1.add(jMenu6);

        jMenu12.setText("Transaksi");

        jMenuItem5.setText("Surat Masuk");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuItem5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem5KeyPressed(evt);
            }
        });
        jMenu12.add(jMenuItem5);

        jMenu13.setText("Surat Keluar");

        jMenuItem6.setText("Surat Keterangan");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuItem6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem6KeyPressed(evt);
            }
        });
        jMenu13.add(jMenuItem6);

        jMenuItem7.setText("Surat Permohonan");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuItem7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem7KeyPressed(evt);
            }
        });
        jMenu13.add(jMenuItem7);

        jMenuItem8.setText("Surat Tugas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuItem8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem8KeyPressed(evt);
            }
        });
        jMenu13.add(jMenuItem8);

        jMenu12.add(jMenu13);

        jMenuBar1.add(jMenu12);

        jMenu14.setText("Laporan");

        jMenu15.setText("Surat Masuk");

        jMenuItem9.setText("Laporan Perbulan");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuItem9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem9KeyPressed(evt);
            }
        });
        jMenu15.add(jMenuItem9);

        jMenuItem10.setText("Laporan Pertahun");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuItem10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem10KeyPressed(evt);
            }
        });
        jMenu15.add(jMenuItem10);

        jMenu14.add(jMenu15);

        jMenu16.setText("Surat Keterangan");

        jMenuItem11.setText("Laporan Perbulan");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenuItem11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem11KeyPressed(evt);
            }
        });
        jMenu16.add(jMenuItem11);

        jMenuItem12.setText("Laporan Pertahun");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenuItem12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem12KeyPressed(evt);
            }
        });
        jMenu16.add(jMenuItem12);

        jMenu14.add(jMenu16);

        jMenu17.setText("Surat Permohonan");

        jMenuItem13.setText("Laporan Perbulan");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenuItem13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem13KeyPressed(evt);
            }
        });
        jMenu17.add(jMenuItem13);

        jMenuItem14.setText("Laporan Pertahun");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenuItem14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem14KeyPressed(evt);
            }
        });
        jMenu17.add(jMenuItem14);

        jMenu14.add(jMenu17);

        jMenu18.setText("Surat Tugas");

        jMenuItem15.setText("Laporan Perbulan");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenuItem15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem15KeyPressed(evt);
            }
        });
        jMenu18.add(jMenuItem15);

        jMenuItem16.setText("Laporan Pertahun");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenuItem16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem16KeyPressed(evt);
            }
        });
        jMenu18.add(jMenuItem16);

        jMenu14.add(jMenu18);

        jMenuBar1.add(jMenu14);

        jMenu19.setText("Pengaturan");

        jMenuItem17.setText("Logout");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenuItem17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuItem17KeyPressed(evt);
            }
        });
        jMenu19.add(jMenuItem17);

        jMenuBar1.add(jMenu19);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FUser user =  new FUser();
        jDesktopPane1.add(user);
        user.setVisible(true);
        user.setSize(800, 600);
        user.setLocation(jDesktopPane1.getWidth()/2 - user.getWidth()/2,
                jDesktopPane1.getHeight()/2-user.getHeight()/2);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FUser user =  new FUser();
            jDesktopPane1.add(user);
            user.setVisible(true);
            user.setSize(800, 600);
            user.setLocation(jDesktopPane1.getWidth()/2 - user.getWidth()/2,
                    jDesktopPane1.getHeight()/2-user.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem2KeyPressed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        FLogin form_login = new FLogin();
        form_login.setVisible(true);
        form_login.setSize(715, 500);
        form_login.setLocationRelativeTo(null);
        form_login.setTitle("Form Login");
        this.dispose();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem17KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLogin form_login = new FLogin();
            form_login.setVisible(true);
            form_login.setSize(715, 500);
            form_login.setLocationRelativeTo(null);
            form_login.setTitle("Form Login");
            this.dispose();
        }
    }//GEN-LAST:event_jMenuItem17KeyPressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FGuru guru =  new FGuru();
        jDesktopPane1.add(guru);
        guru.setVisible(true);
        guru.setSize(800, 600);
        guru.setLocation(jDesktopPane1.getWidth()/2 - guru.getWidth()/2,
                jDesktopPane1.getHeight()/2-guru.getHeight()/2);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FGuru guru =  new FGuru();
            jDesktopPane1.add(guru);
            guru.setVisible(true);
            guru.setSize(800, 600);
            guru.setLocation(jDesktopPane1.getWidth()/2 - guru.getWidth()/2,
                    jDesktopPane1.getHeight()/2-guru.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem3KeyPressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FSurat_Masuk surat_masuk =  new FSurat_Masuk();
        jDesktopPane1.add(surat_masuk);
        surat_masuk.setVisible(true);
        surat_masuk.setSize(800, 600);
        surat_masuk.setLocation(jDesktopPane1.getWidth()/2 - surat_masuk.getWidth()/2,
                jDesktopPane1.getHeight()/2-surat_masuk.getHeight()/2);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FSurat_Masuk surat_masuk =  new FSurat_Masuk();
            jDesktopPane1.add(surat_masuk);
            surat_masuk.setVisible(true);
            surat_masuk.setSize(800, 600);
            surat_masuk.setLocation(jDesktopPane1.getWidth()/2 - surat_masuk.getWidth()/2,
                    jDesktopPane1.getHeight()/2-surat_masuk.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem5KeyPressed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Masuk_Perbulan laporan_sm_perbulan = new FLaporan_Surat_Masuk_Perbulan();
        jDesktopPane1.add(laporan_sm_perbulan);
        laporan_sm_perbulan.setVisible(true);
        laporan_sm_perbulan.setSize(800, 600);
        laporan_sm_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_sm_perbulan.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_sm_perbulan.getHeight()/2);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FSiswa siswa = new FSiswa();
        jDesktopPane1.add(siswa);
        siswa.setVisible(true);
        siswa.setSize(800, 600);
        siswa.setLocation(jDesktopPane1.getWidth()/2 - siswa.getWidth()/2,
            jDesktopPane1.getHeight()/2-siswa.getHeight()/2);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem9KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Masuk_Perbulan laporan_sm_perbulan = new FLaporan_Surat_Masuk_Perbulan();
            jDesktopPane1.add(laporan_sm_perbulan);
            laporan_sm_perbulan.setVisible(true);
            laporan_sm_perbulan.setSize(800, 600);
            laporan_sm_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_sm_perbulan.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_sm_perbulan.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem9KeyPressed

    private void jMenuItem4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FSiswa siswa = new FSiswa();
            jDesktopPane1.add(siswa);
            siswa.setVisible(true);
            siswa.setSize(800, 600);
            siswa.setLocation(jDesktopPane1.getWidth()/2 - siswa.getWidth()/2,
                jDesktopPane1.getHeight()/2-siswa.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem4KeyPressed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        FSurat_Keterangan surat_keterangan = new FSurat_Keterangan();
        jDesktopPane1.add(surat_keterangan);
        surat_keterangan.setVisible(true);
        surat_keterangan.setSize(800, 600);
        surat_keterangan.setLocation(jDesktopPane1.getWidth()/2 - surat_keterangan.getWidth()/2,
        jDesktopPane1.getHeight()/2-surat_keterangan.getHeight()/2);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FSurat_Keterangan surat_keterangan = new FSurat_Keterangan();
            jDesktopPane1.add(surat_keterangan);
            surat_keterangan.setVisible(true);
            surat_keterangan.setSize(800, 600);
            surat_keterangan.setLocation(jDesktopPane1.getWidth()/2 - surat_keterangan.getWidth()/2,
            jDesktopPane1.getHeight()/2-surat_keterangan.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem6KeyPressed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        FSurat_Permohonan surat_permohonan = new FSurat_Permohonan();
        jDesktopPane1.add(surat_permohonan);
        surat_permohonan.setVisible(true);
        surat_permohonan.setSize(800, 600);
        surat_permohonan.setLocation(jDesktopPane1.getWidth()/2 - surat_permohonan.getWidth()/2,
        jDesktopPane1.getHeight()/2-surat_permohonan.getHeight()/2);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FSurat_Permohonan surat_permohonan = new FSurat_Permohonan();
            jDesktopPane1.add(surat_permohonan);
            surat_permohonan.setVisible(true);
            surat_permohonan.setSize(800, 600);
            surat_permohonan.setLocation(jDesktopPane1.getWidth()/2 - surat_permohonan.getWidth()/2,
            jDesktopPane1.getHeight()/2-surat_permohonan.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem7KeyPressed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        FSurat_Tugas surat_tugas = new FSurat_Tugas();
        jDesktopPane1.add(surat_tugas);
        surat_tugas.setVisible(true);
        surat_tugas.setSize(800, 600);
        surat_tugas.setLocation(jDesktopPane1.getWidth()/2 - surat_tugas.getWidth()/2,
        jDesktopPane1.getHeight()/2-surat_tugas.getHeight()/2);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem8KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FSurat_Tugas surat_tugas = new FSurat_Tugas();
            jDesktopPane1.add(surat_tugas);
            surat_tugas.setVisible(true);
            surat_tugas.setSize(800, 600);
            surat_tugas.setLocation(jDesktopPane1.getWidth()/2 - surat_tugas.getWidth()/2,
            jDesktopPane1.getHeight()/2-surat_tugas.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem8KeyPressed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Masuk_Pertahun laporan_sm_pertahun = new FLaporan_Surat_Masuk_Pertahun();
        jDesktopPane1.add(laporan_sm_pertahun);
        laporan_sm_pertahun.setVisible(true);
        laporan_sm_pertahun.setSize(800, 600);
        laporan_sm_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_sm_pertahun.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_sm_pertahun.getHeight()/2);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem10KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Masuk_Pertahun laporan_sm_pertahun = new FLaporan_Surat_Masuk_Pertahun();
            jDesktopPane1.add(laporan_sm_pertahun);
            laporan_sm_pertahun.setVisible(true);
            laporan_sm_pertahun.setSize(800, 600);
            laporan_sm_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_sm_pertahun.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_sm_pertahun.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem10KeyPressed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Keterangan_Pertahun laporan_sk_pertahun = new FLaporan_Surat_Keterangan_Pertahun();
        jDesktopPane1.add(laporan_sk_pertahun);
        laporan_sk_pertahun.setVisible(true);
        laporan_sk_pertahun.setSize(800, 600);
        laporan_sk_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_sk_pertahun.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_sk_pertahun.getHeight()/2);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem12KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Keterangan_Pertahun laporan_sk_pertahun = new FLaporan_Surat_Keterangan_Pertahun();
            jDesktopPane1.add(laporan_sk_pertahun);
            laporan_sk_pertahun.setVisible(true);
            laporan_sk_pertahun.setSize(800, 600);
            laporan_sk_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_sk_pertahun.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_sk_pertahun.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem12KeyPressed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        //sk perbulan
        FLaporan_Surat_Keterangan_Perbulan laporan_sk_perbulan = new FLaporan_Surat_Keterangan_Perbulan();
        jDesktopPane1.add(laporan_sk_perbulan);
        laporan_sk_perbulan.setVisible(true);
        laporan_sk_perbulan.setSize(800, 600);
        laporan_sk_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_sk_perbulan.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_sk_perbulan.getHeight()/2);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem11KeyPressed
        // TODO add your handling code here:
        //sk perbulan
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Keterangan_Perbulan laporan_sk_perbulan = new FLaporan_Surat_Keterangan_Perbulan();
            jDesktopPane1.add(laporan_sk_perbulan);
            laporan_sk_perbulan.setVisible(true);
            laporan_sk_perbulan.setSize(800, 600);
            laporan_sk_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_sk_perbulan.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_sk_perbulan.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem11KeyPressed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Permohonan_Perbulan laporan_sp_perbulan = new FLaporan_Surat_Permohonan_Perbulan();
        jDesktopPane1.add(laporan_sp_perbulan);
        laporan_sp_perbulan.setVisible(true);
        laporan_sp_perbulan.setSize(800, 600);
        laporan_sp_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_sp_perbulan.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_sp_perbulan.getHeight()/2);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem13KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Permohonan_Perbulan laporan_sp_perbulan = new FLaporan_Surat_Permohonan_Perbulan();
            jDesktopPane1.add(laporan_sp_perbulan);
            laporan_sp_perbulan.setVisible(true);
            laporan_sp_perbulan.setSize(800, 600);
            laporan_sp_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_sp_perbulan.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_sp_perbulan.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem13KeyPressed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Permohonan_Pertahun laporan_sp_pertahun = new FLaporan_Surat_Permohonan_Pertahun();
        jDesktopPane1.add(laporan_sp_pertahun);
        laporan_sp_pertahun.setVisible(true);
        laporan_sp_pertahun.setSize(800, 600);
        laporan_sp_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_sp_pertahun.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_sp_pertahun.getHeight()/2);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem14KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Permohonan_Pertahun laporan_sp_pertahun = new FLaporan_Surat_Permohonan_Pertahun();
            jDesktopPane1.add(laporan_sp_pertahun);
            laporan_sp_pertahun.setVisible(true);
            laporan_sp_pertahun.setSize(800, 600);
            laporan_sp_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_sp_pertahun.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_sp_pertahun.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem14KeyPressed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Tugas_Perbulan laporan_st_perbulan = new FLaporan_Surat_Tugas_Perbulan();
        jDesktopPane1.add(laporan_st_perbulan);
        laporan_st_perbulan.setVisible(true);
        laporan_st_perbulan.setSize(800, 600);
        laporan_st_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_st_perbulan.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_st_perbulan.getHeight()/2);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem16KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Tugas_Pertahun laporan_st_pertahun = new FLaporan_Surat_Tugas_Pertahun();
            jDesktopPane1.add(laporan_st_pertahun);
            laporan_st_pertahun.setVisible(true);
            laporan_st_pertahun.setSize(800, 600);
            laporan_st_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_st_pertahun.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_st_pertahun.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem16KeyPressed

    private void jMenuItem15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuItem15KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            FLaporan_Surat_Tugas_Perbulan laporan_st_perbulan = new FLaporan_Surat_Tugas_Perbulan();
            jDesktopPane1.add(laporan_st_perbulan);
            laporan_st_perbulan.setVisible(true);
            laporan_st_perbulan.setSize(800, 600);
            laporan_st_perbulan.setLocation(jDesktopPane1.getWidth()/2 - laporan_st_perbulan.getWidth()/2,
            jDesktopPane1.getHeight()/2-laporan_st_perbulan.getHeight()/2);
        }
    }//GEN-LAST:event_jMenuItem15KeyPressed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        FLaporan_Surat_Tugas_Pertahun laporan_st_pertahun = new FLaporan_Surat_Tugas_Pertahun();
        jDesktopPane1.add(laporan_st_pertahun);
        laporan_st_pertahun.setVisible(true);
        laporan_st_pertahun.setSize(800, 600);
        laporan_st_pertahun.setLocation(jDesktopPane1.getWidth()/2 - laporan_st_pertahun.getWidth()/2,
        jDesktopPane1.getHeight()/2-laporan_st_pertahun.getHeight()/2);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
